---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add zabbix official apt repos
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "deb http://repo.zabbix.com/zabbix/2.4/ubuntu trusty main"
    - "deb-src http://repo.zabbix.com/zabbix/2.4/ubuntu trusty main"
  when: ansible_os_family == "Debian"

- name: Add zabbix apt key(s)
  apt_key: url="http://repo.zabbix.com/zabbix-official-repo.key"
  when: ansible_os_family == "Debian"

- name: Install packages
  tags: 
    - pkg_install
  pacman: name="{{ item }}" state=present
  with_items:
    - "{{ zabbix_agent_packages }}"
  when: ansible_os_family == "ArchLinux"

- name: Install packages
  tags:
    - pkg_install
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - "{{ zabbix_agent_packages }}"
  when: ansible_os_family == "Debian"

- name: Enable zabbix agent
  tags:
    - pkg_install
  service: name={{ zabbix_agent_service_name }} enabled=yes

- name: Make sure helper script directory exists
  file: path={{ zabbix_agent_helper_script_dir }} state=directory
        owner=zabbix group=zabbix mode=770

- include: mdadm.yml
  when: zabbix_agent_helper_mdadm

- include: nginx.yml
  when: zabbix_agent_helper_nginx

- include: php_fpm.yml
  when: zabbix_agent_helper_php_fpm

- include: postfix.yml
  when: zabbix_agent_helper_postfix

- include: postgres.yml
  when: zabbix_agent_helper_postgres

- include: zfs.yml
  when: zabbix_agent_helper_zfs

- name: Setup zabbix sudoers privileges
  tags:
    - pkg_config
  template: src=sudoers.d_zabbix dest=/etc/sudoers.d/zabbix
            owner=root group=root mode=0440 validate='visudo -cf %s'

- name: Setup main agent configs
  tags:
    - pkg_config
  template: src="{{ item }}" dest="/etc/zabbix/{{ item }}"
            owner=zabbix group=zabbix mode=0440
  with_items:
    - zabbix_agent.conf
    - zabbix_agentd.conf
  notify:
    - restart zabbix-agent

- debug: msg={{ zabbix_agent_helper_zfs }}
