---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  tags: 
    - pkg_install
  pacman: name={{ item }} state=present
  with_items:
    - "{{ zabbix_agent_packages }}"
  when: ansible_os_family == "ArchLinux"

- name: Install packages
  tags:
    - pkg_install
  apt: name={{ item }} state=present
  with-items:
    - "{{ ansible_agent_packages }}"
  when: ansible_os_family == "Debian"

- name: Enable zabbix agent
  tags:
    - pkg_install
  service: name={{ zabbix_agent_service_name }} enabled=yes

- name: Make sure helper script directory exists
  file: path={{ zabbix_agent_helper_script_dir }} state=directory
        owner=zabbix group=zabbix mode=770

- name: Setup mdadm helper script
  copy: src=/etc/ansible/roles/zabbix_agent/templates/zabbix_mdraid.sh dest="{{ zabbix_agent_helper_script_dir }}"
        owner=zabbix group=zabbix mode=0550

- name: Setup nginx helper script
  copy: src=/etc/ansible/roles/zabbix_agent/templates/nginx-check.sh dest="{{ zabbix_agent_helper_script_dir }}"
        owner=zabbix group=zabbix mode=0550
  when: nginx is defined and nginx

- name: Setup php-fpm helper script
  copy: src=/etc/ansible/roles/zabbix_agent/templates/php-fpm-check.sh dest="{{ zabbix_agent_helper_script_dir }}"
        owner=zabbix group=zabbix mode=0550
  when: php_fpm is defined and php_fpm

- name: Setup zabbix agent role (for pgsql template)
  postgresql_user: name=zabbix state=present
  when: postgres is defined and postgres

- name: Setup postgres find database script
  copy: src=/etc/ansible/roles/zabbix_agent/templates/find_dbname.sh dest="{{ zabbix_agent_helper_script_dir }}"
        owner=zabbix group=zabbix mode=0550
  when: postgres is defined and postgres

- name: Setup postgres find database table script
  copy: src=/etc/ansible/roles/zabbix_agent/templates/find_dbname_table.sh dest="{{ zabbix_agent_helper_script_dir }}"
        owner=zabbix group=zabbix mode=0550
  when: postgres is defined and postgres

- name: Setup postfix helper script
  copy: src=/etc/ansible/roles/zabbix_agent/templates/postfix.sh dest="{{ zabbix_agent_helper_script_dir }}"
        owner=zabbix group=zabbix mode=0550
  when: real_email is defined and real_email

- name: Allow zabbix access to postfix directory
  acl: name=/etc/postfix entity=zabbix etype=user permissions="rx" state=present
  when: real_email is defined and real_email

- name: Allow zabbix access to postfix config
  acl: name=/etc/postfix/main.cf entity=zabbix etype=user permissions="r" state=present
  when: real_email is defined and real_email

- name: Setup postfix helper script cron job
  cron: name="Zabbix Postfix Monitor" state=present
        job="/opt/bin/zabbix/postfix.sh"
        minute="*/15"
  when: real_email is defined and real_email

- name: Setup zabbix sudoers privileges
  tags:
    - pkg_config
  template: src=sudoers.d_zabbix dest=/etc/sudoers.d/zabbix
            owner=root group=root mode=0440 validate='visudo -cf %s'

- name: Setup main agent configs
  tags:
    - pkg_config
  template: src={{ item }} dest=/etc/zabbix
            owner=zabbix group=zabbix mode=0440
  with_items:
    - zabbix_agent.conf
    - zabbix_agentd.conf
  notify:
    - restart zabbix-agent

- name: Setup agent user variables
  tags:
    - pkg_config
  copy: src=/etc/ansible/roles/zabbix_agent/templates/{{ item }} dest=/etc/zabbix/zabbix_agentd.conf.d
        owner=zabbix group=zabbix mode=0440
  with_items:
    - md.conf
    - zfs.conf
    - nginx-params.conf
    - php-fpm-params.conf
    - userparameter_pgsql.conf
    - postfix-params.conf
  notify:
    - restart zabbix-agent

